# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_by_user',
            new_name='review_for_book',
        ),
    ]
