# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0002_auto_20170124_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.IntegerField(),
        ),
    ]
